### ISSUE TITLE
no `client` in SosNode

### ISSUE THREAD

**Issue by ret2libc** [sosreport/sos-collector#9]
Since last commit (https://github.com/sosreport/sos-collector/commit/e1d6bd055137cb1505627aa809281730ca138aa9) I see this message when running: `./sos-collector --no-local --nodes "192.168.121.107" --cluster-type kubernetes`

```
...
sos-collector ASSUMES that SSH keys are installed on all nodes unless the
--password option is provided.

Traceback (most recent call last):
  File "./sos-collector", line 117, in <module>
    sc = SosCollector(config)
  File "/home/rschiron/workspace/analyses/sos/sos-collector-git/soscollector/sos_collector.py", line 61, in __init__
    self.prep()
  File "/home/rschiron/workspace/analyses/sos/sos-collector-git/soscollector/sos_collector.py", line 331, in prep
    self.master = SosNode('localhost', self.config)
  File "/home/rschiron/workspace/analyses/sos/sos-collector-git/soscollector/sosnode.py", line 61, in __init__
    self.sftp = self.client.open_sftp()
AttributeError: SosNode instance has no attribute 'client'
```

**Comment by TurboTurtle** [comment]
Thanks for the report. This was a trivial fix on its own, though resolving that showed another underlying issue for the exact way you're invoking sos-collector that, while an obvious usage of it, was one I was not testing before.

With commit a02c457 these should all be resolved, can you test out the latest master to see if that works for you?

**Comment by ret2libc** [comment]
Thanks, it works!
